batch_size: 1
num_epochs: 10
learning_rate: 0.001
training: True
explore_data: False
test_loss: False
inspect_model: True
resources:
  train_worker: 4
  val_worker: 2
weights:
  load: False
  save: True
  file: StixelNExT_legendary-mountain-17_epoch-6_loss-56299.47203177295.pth
logging:
  activate: False
  project: Stixel-Multicut
  dataset: Multicut_data
  architecture: ConvNeXt
