batch_size: 2
data_path: /home/marcel/workspace/datasets
# /home/marcel/workspace/datasets
# C:\Users\marce\Documents\datasets
dataset: ameise
explore_data: true
grid_step: 4
img_height: 376
img_width: 1248
inspect_model: true
learning_rate: 0.001
load_weights: true
logging:
  activate: false
  project: Stixel-Multicut
loss:
  alpha: 1.0
  beta: 1.0
  gamma: false
  delta: 1.0
nn:
  depths:
  - 6
  - 3
  drop_p: 0.0
  stem_features: 64
  widths:
  - 96
  - 192
  - 384
  - 768
num_epochs: 100
pred_threshold: 0.2
resources:
  test_worker: 2
  train_worker: 4
  val_worker: 2
test_loss: true
training: false
weights_file: StixelNExT_dandy-butterfly-178_epoch-8_test-error-0.05427330359816551.pth
early_stopping:
  tolerance: 16
  min_delta: 0.001
num_obj_per_col: 42
max_dist: 45
