batch_size: 16
num_epochs: 25
learning_rate: 0.001
training: True
explore_data: False
test_loss: False
inspect_model: True
resources:
  train_worker: 10
  val_worker: 5
  test_worker: 2
weights:
  load: False
  save: True
  file: StixelNExT_legendary-mountain-17_epoch-6_loss-56299.47203177295.pth
logging:
  activate: True
  project: Stixel-Multicut
  dataset: Multicut_data
  architecture: ConvNeXt
